Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
#Provision with Ansible
  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "ansible/playbook.yml"
       ansible.sudo = true
  end
end
